# Generated by Django 3.0.6 on 2020-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_category', models.CharField(max_length=30)),
                ('item_topping_num', models.IntegerField(default=0)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Large',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_name', models.CharField(max_length=30)),
                ('large_category', models.CharField(max_length=30)),
                ('large_topping_num', models.IntegerField(default=0)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_name', models.CharField(max_length=30)),
                ('small_category', models.CharField(max_length=30)),
                ('small_topping_num', models.IntegerField(default=0)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=30)),
            ],
        ),
    ]
