# Generated by Django 3.0.6 on 2020-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=30)),
                ('size_category', models.CharField(max_length=30)),
                ('size_topping_num', models.IntegerField(default=0)),
                ('size_small_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size_large_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Large',
        ),
        migrations.DeleteModel(
            name='Small',
        ),
    ]
