# Generated by Django 3.0.6 on 2020-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200613_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topping_name', models.CharField(max_length=30)),
            ],
        ),
    ]
