# Generated by Django 3.0.6 on 2020-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
