# Generated by Django 3.0.6 on 2020-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_confirmed_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed',
            name='order_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
