# Generated by Django 3.0.6 on 2020-06-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_topping_num',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size_topping_num',
        ),
    ]
